### ISSUE TITLE
Standalone option fails to knit

### ISSUE THREAD

**Issue by imanuelcostigan** [MangoTheCat/rmdshower#44]
Here's the output block in my yaml header:

```yaml
output: 
  rmdshower::shower_presentation:
    self_contained: true
    theme: "material"
    incremental: true
    katex: true
    ratio: "4x3"
```

This returns the following error when knitting:

```
pandoc.exe: Could not fetch slides_files/rmdshower/package/styles/screen-4x3.css
slides_files/rmdshower/package/styles/screen-4x3.css: openBinaryFile: does not exist (No such file or directory)
Error: pandoc document conversion failed with error 67
In addition: Warning message:
running command '"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS slides.utf8.md --to revealjs --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures --output slides.html --smart --email-obfuscation none --self-contained --template "C:\RLibrary\rmdshower\rmarkdown\templates\shower\resources\default.html" --incremental --slide-level 2 "--variable=ratio:4x3" "--variable=katex:yes" --mathjax --variable "mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" "--variable=shower-url:slides_files\rmdshower" "--variable=theme:material" "--variable=shower-theme-url:slides_files/rmdshower" --highlight-style pygments' had status 67 
Execution halted
```
